### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 377: illegal multibyte sequence

### ISSUE THREAD

**Issue by roshines** [turnipsoup/ctfwriteups#1]
```

import json

json_file = json.loads(open("clicks.json","r").read())

for a in json_file:
	try:
		click_info = a["_source"]["layers"]["http"]["http.file_data"]
		print(click_info)
	except:
		pass
```

我用这个脚本的时候会报错，所以改成了json_file = json.loads(open("clicks.json","rb").read())

**Comment by turnipsoup** [comment]
Use "r" not "rb" during open. "rb" is for raw bytes, "r" is for text. 

A copy of my JSON is here for you to look at: https://gist.github.com/turnipsoup/63928dd3c94aa45d50e3017bf915a28e
